### ISSUE TITLE
Hope to support multi-profile in new launcher

### ISSUE THREAD

**Issue by sGxOxDs** [mintnick/eve-settings-manager#1]
![image](https://github.com/mintnick/eve-settings-manager/assets/62545840/cee2d231-3ffe-4f2b-a1fe-be25407f5fa8)
![image](https://github.com/mintnick/eve-settings-manager/assets/62545840/f0c4c5c6-8ebc-44d0-84a3-91d04d7ef95a)

**Comment by mintnick** [comment]
Thank you for the advice.
Cannot promise when I will update the project, but that will be on the top of the todo list :smiley:

**Comment by Bombe** [comment]
I came across this project today and simply had to add that: https://github.com/Bombe/eve-settings-manager/tree/feature/use-profiles. If you’re okay with these changes, @mintnick, I’d massage them into a nicer pull request.

**Comment by mintnick** [comment]
> I came across this project today and simply had to add that: https://github.com/Bombe/eve-settings-manager/tree/feature/use-profiles. If you’re okay with these changes, @mintnick, I’d massage them into a nicer pull request.

That's wonderful! I just merged the UI update. It looks much better.
I'm more than happy to invite you as collaborator. Glad to see contribution from the community!

**Comment by Bombe** [comment]
Happy to be on board! I’m also glad to see that not everyone is completely ignoring people playing EVE on macOS. 😁 

I’ll get that use-profile branch in a nice shape and create another PR for it, probably later today. 🙂

**Comment by mintnick** [comment]
The feature has beed added in v1.1.1

![Screenshot 2024-01-31 at 07 48 24](https://github.com/mintnick/eve-settings-manager/assets/14357052/291cff8b-4b5b-4ffe-b65a-297afb0768aa)
